name: Under50
version: ${project.version}
main: com.deprecatednether.bukkit.under50.UnderFifty
commands:
  fly:
    description: Toggle flight mode
  gamemode:
    description: Set your gamemode
    aliases: [gm]
  list:
    description: Get a list of online players
  tp:
    description: Teleport to a player
    aliases: [teleport]
  kick:
    description: Kick a player
  bcast:
    description: Broadcast's a server message
